name: Deploy to GitHub pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0 # Fetch all history
      - name: Apply configurations
        run: |
          cp quartz.config.ts quartz.layout.ts quartz
          # 清空 submodule 的 content 目录，只使用根目录的 content
          rm -rf quartz/content/*
          cp -rf content/* quartz/content/
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: quartz/package-lock.json
      - name: Install Node.js dependencies
        working-directory: quartz
        run: npm ci --omit=dev
      - name: Build website
        run: npx quartz build -d ../content -o public
        working-directory: quartz
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: quartz/public

  # Deployment job
  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/main'}}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
      actions: read     # to download an artifact uploaded by `actions/upload-pages-artifact@v3`
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
